call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
call pathogen#infect()

" Random basic settings
let g:tagbar_usearrows = 1
let mapleader = ","
set mouse=a
set shiftwidth=4
set number
set autoindent
set smarttab
set tabstop=4
set expandtab
set incsearch
set hlsearch
set noswapfile
set nowritebackup 
set nocompatible
set encoding=utf-8
set termencoding=utf-8
set laststatus=2
set cursorline

" Ignore uneccessary files
set wildignore+=__pycache__
set wildignore+=*.pyc
set wildignore+=node_modules

" Show max text width
set textwidth=80
set colorcolumn=80

" Gui (gVim) options
set guioptions-=m " No menu bar
set guioptions-=T " No toolbar
set guioptions-=r " No right-hand side scrollbar
set guioptions-=L " No left-hand side scrollbar
set linespace=3 " Nicer lineheight

" Make sure F11 also works in gVim
map <silent> <F11>
\    :call system("wmctrl -ir " . v:windowid . " -b toggle,fullscreen")<CR>

" Show git status in statusline
set statusline+=%{fugitive#statusline()}

" Enable colorscheme and 256 colors
colorscheme molokai
syntax on
set term=xterm-256color
set t_Co=256

" Vim powerline config
let g:Powerline_symbols = 'unicode'
let g:Powerline_colorscheme = 'solarized256'

" CtrlP cobfig
let g:ctrlp_max_height = 20

" Enable pyflakes
filetype on
filetype plugin on

" TagBar
noremap <leader>t <Esc>:TagbarToggle<CR>
noremap <leader>y <Esc>:TagbarShowTag<CR>

" NERDTree
noremap <leader>z <Esc>:NERDTreeToggle<CR>
noremap <leader>a <Esc>:NERDTreeFind<CR>

" Tabs
noremap <leader>/ <Esc>:tabn<CR>
noremap <leader>. <Esc>:tabp<CR>
noremap <leader>p <Esc>:tabnew<CR>
noremap <leader>o <Esc>:tabclose<CR>

" Undo/Redo
noremap <leader>u <Esc>:undo<CR>
noremap <leader>r <Esc>:redo<CR>

" Save file as sudo
ca w!! %!sudo tee %

" Unmap arrow keys
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
