" Jaapz's vim config.
"
filetype off

" Load pathogen plugin management
call pathogen#runtime_append_all_bundles()
call pathogen#infect()
call pathogen#helptags()

source ~/.vim/plugins/autotag.vim

" Random basic settings
let mapleader = ","
set number " Always show line numbers
set nocompatible " No vi compatibility
set cursorline " Highlight current line
set so=5

" Search settings set hlsearch
set incsearch

" Split the Correct(tm) way.
set splitright

" Conceallevels
set conceallevel=2
let g:syntax_js=['function', 'return', 'semicolon', 'proto']
set foldmethod=syntax
set foldlevel=99

" Pythonic indents
set shiftwidth=4
set autoindent
set smarttab
set expandtab
set tabstop=4
set softtabstop=4

" Correct unicode encoding
set encoding=utf-8
set termencoding=utf-8
set laststatus=2
set cursorline

" Ignore uneccessary files
set wildignore+=__pycache__
set wildignore+=*.pyc
set wildignore+=node_modules
set wildignore+=*/app/cache/*
set wildignore+=*/vendor/*

" Show max text width
set textwidth=80
set colorcolumn=80

" Only wrap comments
set formatoptions-=t

" No backups
set nowritebackup 

" Gui (gVim) options
set guioptions-=m " No menu bar
set guioptions-=T " No toolbar
set guioptions-=r " No right-hand side scrollbar
set guioptions-=L " No left-hand side scrollbar
set linespace=3 " Nicer lineheight
set guifont=Monospace\ 10

" Why is this not default.
set backspace=indent,eol,start

" Hack to make sure F11 also works in gVim
map <silent> <F11>
\    :call system("wmctrl -ir " . v:windowid . " -b toggle,fullscreen")<CR>

" Enable colorscheme and 256 colors
" colorscheme molokai
colorscheme vombatidae
syntax on
set t_Co=256

" Vim-airline config
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_theme='wombat'
let g:bufferline_echo=0
set laststatus=2 " Always show statusline
set noshowmode

" CtrlP config
let g:ctrlp_max_height = 20
let g:ctrlp_max_files = 0
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
map <leader>t :CtrlPTag<cr>
map <C-b> :CtrlPBuffer<CR>

" Use ag!
set grepprg=ag

" Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

" ag is fast enough that CtrlP doesn't need to cache
let g:ctrlp_use_caching = 0

" Enable pyflakes
filetype on
filetype plugin indent on

" Python mode settings
let g:pymode_lint_checker = "flake8"
let g:pymode_lint_cwindow = 0
let g:pymode_lint_ignore = "F0401"
let g:pymode_rope_complete_on_dot = 0
let g:pymode_rope_completion = 0
let g:pymode_rope_goto_definition_cmd = 'e'
let g:pymode_rope_goto_definition_bind = "<C-]>"
let g:pymode_doc = 0
let g:pymode_run = 0

" Syntastic config
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_always_populate_loc_list = 1
noremap <leader>ne <Esc>:lnext<CR>
noremap <leader>pe <Esc>:lprev<CR>

" Don't preview documentation for an autocomplete candidate.
set completeopt-=preview

" NERDTree
noremap <leader>z <Esc>:NERDTreeToggle<CR>
noremap <leader>a <Esc>:NERDTreeFind<CR>

" Buffers
noremap <leader>/ <Esc>:bn<CR>
noremap <leader>. <Esc>:bp<CR>
noremap <leader>o <Esc>:bd<CR>

noremap <leader>s <Esc>:w<CR>
inoremap <leader>s <Esc>:w<CR>
vnoremap <leader>s <Esc>:w<CR>

" Save file as sudo
ca w!! %!sudo tee %

" Handy commands
com W w
com Qa qa

" Copy and Paste to system clipboard
vmap <leader>c "+y
vmap <leader>x "+c
map <leader>v <Esc>v"+p

" Unmap arrow keys
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>

set ttyfast
set re=1
set hidden

map <C-J> <Plug>snipMateNextOrTrigger
smap <C-J> <Plug>snipMateNextOrTrigger
