# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="prose"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"
#source /usr/local/bin/virtualenvwrapper.sh

# Make sure the colors are used correctly in vim and the like.
export TERM="screen-256color"

# Useful aliases
alias scon="php app/console" # symfony2 console
alias fucking="sudo" # JUST DO EEET FFS
alias :q='exit'
alias v="vim --remote-tab"
alias g="gvim --remote-tab"
alias vims="vim --servername VIM"
alias vbm-update-cache="vbm \"app/update-cache.sh --prod\""

# Push files from local directory to both vbm servers.
function push-vbm () {
    scp $1 sshvbmdev@server01.sst-hosting.nl:$1
    scp $1 sshvbmdev@server02.sst-hosting.nl:$1
}

function demo-skk () {
    scp $1 demo-skk@silkekinderkleding.nl:~/web/$1
}

function live-skk () {
    scp $1 www-skk@silkekinderkleding.nl:~/web/$1
}

function push-ssh-key () {
    cat ~/.ssh/id_rsa.pub | ssh $1 'cat >> .ssh/authorized_keys'
}

function vbm (){
    ssh sshvbmdev@server01.sst-hosting.nl $1
    ssh sshvbmdev@server02.sst-hosting.nl $1
}
