# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="steeef"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Autostart tmux
# ZSH_TMUX_AUTOSTART="true"
# ZSH_TMUX_AUTOCONNECT="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-extras battery extract colorize python urltools)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"
#source /usr/local/bin/virtualenvwrapper.sh
#
if [ -n "$TMUX" ]; then
    export TERM=screen-256color
else
    export TERM=gnome-256color
fi

# Useful aliases
alias fucking="sudo" # JUST DO EEET FFS
alias :q='exit'
alias v="vim --remote-tab"
alias g="gvim --remote-tab"
alias vims="vim --servername VIM"
alias pynt="noglob pynt"
alias tests="pynt tests"
alias karma="pynt js"
alias web="x-www-browser"
alias irssi-remote="ssh jaapz@broekhuizen.nu -t 'tmux attach -t irssi'"
alias todo="cat ~/todo"
alias etodo="vim ~/todo"

source ~/programming/other/virtualenv-tools/virtualenv.sh
source ~/programming/other/zsh-scripts/start-ssh-agent.sh
source ~/programming/other/zsh-scripts/autostart-tmux.sh
source ~/programming/other/zsh-scripts/push-ssh-key.sh

function syncer() {
    if [ -n $1 ]; then
        ENV=$1
    else
        ENV='prod'
    fi

    cd ~/programming/syncer
    export SYNCER_ENV=$ENV
    activate
    pynt setup
}

function mbo() {
    if [ -n $1 ]; then
        ENV=$1
    else
        ENV='prod'
    fi

    cd ~/programming/mijnbaopt
    export MIJNBAOPT_ENV=$ENV
    export MIJNBAOPT_DIR='/home/jaapz/programming/mijnbaopt'
    export MIJNBAOPT_VENV='/home/jaapz/programming/mijnbaopt/.env'
    activate
}

function bam() {
    if [ -n $1 ]; then
        ENV=$1
    else
        ENV='prod'
    fi

    cd ~/programming/account-manager
    export ACCOUNTMANAGER_ENV=$ENV
    activate
}

function thesis() {
    cd ~/documents/bachelor-thesis-report
    mupdf ~/documents/bachelor-thesis-report/bachelor-thesis-report.pdf &
    vim bachelor-thesis-report.tex
}
